services:
  - iis

build: false

test_script:
  - ps: . .\build.ps1

environment:
  NuGetApiKey:
    secure: Wt2Q6bJg+ozZ24LUyGSlYaj1RDpfh+A4s7JhKfqhY2KfbU30rv5EmgnJptiRlXWL

skip_commits:
  message: /updated doc.*|update doc.*s/
